- name: Create Jenkins jobs
  hosts: localhost
  vars:
    jenkins_url: http://52.201.233.237:8080
    jenkins_user: admin
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: exp_frontend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: '{{jenkins_user}}'

    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: exp_backend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"

    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: parameters
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"

    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: exp_terraform
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"