- name: Create Jenkins jobs
  hosts: localhost
  vars:
    jenkins_url: http://3.84.1.88:8080
    jenkins_user: admin
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: exp-frontend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: '{{jenkins_user}}'
      vars:
        repo_name: exp_frontend

    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: exp-backend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: exp_backend

    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: exp-parameters
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: parameters

    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: exp-terraform
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: exp_terraform
